### ISSUE TITLE
Dataset 구축 및 Training Code Follow Up

### ISSUE THREAD

**Issue by Zerohertz** [Team-BoonMoSa/PANPP#3]
> 🔨 Dead Line 🔨: 2023년 3월 20일

Training Data 및 Test Data 디렉토리 구축하고
모델 학습까지 해오기 !

데이터 디렉토리 구축 및 모델 학습은 [이거](https://github.com/Team-BoonMoSa/PANPP/blob/main/main.ipynb) 참고 ~

**Comment by Zerohertz** [comment]
![4092275918 jpg](https://user-images.githubusercontent.com/42334717/226176830-118f6692-e454-407f-bc12-7e084a23d6c2.png)
![4489290640 jpg](https://user-images.githubusercontent.com/42334717/226176864-07bcfe8f-9096-4317-ba8f-5ffd6e649acb.png)
![4842404680 jpg](https://user-images.githubusercontent.com/42334717/226176909-6d036445-ce37-45c9-beb8-827ffb335f37.png)

**Comment by Zerohertz** [comment]
![2349836195 jpg](https://user-images.githubusercontent.com/42334717/226178096-3b8ba840-26dd-4e66-9ab1-b60e670d9061.png)

STD 모델의 한계? -> YOLO 사용?

**Comment by c0olcode** [comment]
![image](https://user-images.githubusercontent.com/69861207/226347443-59aeeb71-99b0-435a-9dcf-4a53dc3c0408.png)

데이터 전처리할 때 train/test img/gt 개수 맞춰도 계속 파일 못찾는대서,,, 
파일 이름 비교해서 데이터 삭제시키고 다시 훈련 돌리겠슴다

**Comment by woo-ara** [comment]
<img width="683" alt="image" src="https://user-images.githubusercontent.com/69287689/226413058-6536a24e-b973-4c7f-96e5-93474604a0f5.png">

epoch 10으로 학습

**Comment by c0olcode** [comment]
![image](https://user-images.githubusercontent.com/69861207/226435187-7ddc24e8-bb73-428a-abda-85746b58fb99.png)
![image](https://user-images.githubusercontent.com/69861207/226435284-b10a9cdb-a67f-4214-a8e0-dba3bdc828da.png)
![image](https://user-images.githubusercontent.com/69861207/226435463-f46d59bb-b14e-43f9-9922-ff12fbbf2cdd.png)


epoch 10으로 학습 -> 성능은,,, gurim

**Comment by seohl16** [comment]
### 학습 돌리면서 생겼던 이슈 
1. zip 파일 업로드 
-> 해결 : wget & unzip 조합으로 해결 
3. `ModuleNotFoundError: No module named 'models.post_processing.pa.pa' `에러 발생 
-> 해결 : https://github.com/whai362/pan_pp.pytorch/issues/108
-> cpython compile은 안해서 생겼던 에러 
```
cd ./models/post_processing/pa/
python setup.py build_ext --inplace
cd ../boxgen/
python setup.py build_ext --inplace
cd ../../../
echo Done!
```
코드를 실행해서 해결

### Epoch10 돌린 결과 스크린샷

![image](https://user-images.githubusercontent.com/68208055/226517622-8b88272e-388f-40dd-a1ee-5870faf9ca98.png)

Epoch10 loss 0.420, epoch 1 때 0.610에 비해 줄어들었다.
